name = "cloudflare_temp_email"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

routes = [
{ pattern = "tempmail.renhaipi.xyz", custom_domain = true },
]

[vars]
PREFIX = "tmp"
DOMAINS = ["renhaipi.xyz"]
JWT_SECRET = "b7e1f5b1c2d3478ea9d3b6a1f0e9c8d7a6b5c4d3e2f1a9b8"
ADMIN_PASSWORDS = ["200304"]
ENABLE_USER_CREATE_EMAIL = true
ENABLE_USER_DELETE_EMAIL = true

[[d1_databases]]
binding = "DB"
database_name = "tempemail"
database_id = "c498bef2-eb39-4aa6-8a7f-0f2607b1bf28"

DEFAULT_DOMAINS = ["renhaipi.xyz"]
